### ISSUE TITLE
port to cerebral@0.34

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-module-http#5]
see following for refs:
cerebral/cerebral-module-router#86
cerebral/cerebral-module-recorder#7
cerebral/cerebral-module-signal-store#5

**Comment by fvgoto** [comment]
0.34 has also following (dev-)breaking change:
 new [cerebral-provider-modules](https://github.com/cerebral/cerebral/commit/605abe387f48877074de60aad3de59db256f89cb)

---

Meanwhile workaround (at Cerebral controller level):

```
import ModulesProvider from 'cerebral-provider-modules';
import Http from 'cerebral-module-http';
//...
controller.addContextProvider(ModulesProvider);
controller.addModules({
  //...
  ['cerebral-module-http']: Http({ ... })
});
```

(Note: As opposed to [README:20](https://github.com/cerebral/cerebral-module-http/blame/master/README.md#L20), the key has to be `cerebral-module-http`, otherwise the [action factories](https://github.com/cerebral/cerebral-module-http/blob/master/get.js#L9) won't get it.)

**Comment by garth** [comment]
Looks like this has been addressed by https://github.com/cerebral/cerebral-module-http/commit/2423d5d1ca7cb6f3db3985dcdafb1bb9eccd6548

**Comment by christianalfoni** [comment]
Yes, this one is fixed now :)
